[package]
name = "AdventOfRust"
version = "0.1.0"
authors = ["Angus Cheng <baller.industries@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
